# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-07"

[[extensions]]
name = "Order number on Thank you page"
handle = "thank-you-order-number"
type = "ui_extension"
uid = "1c7d146a-0c44-f333-4d5c-929b3279f9ff2f9d9343"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/targets

# Below the Thank you page header (no placement needed), and as a block the
# merchant can move in the checkout editor.
[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.header.render-after"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/apps/build/checkout/capabilities#storefront-api-access
api_access = false

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/apps/build/checkout/capabilities#network-access

network_access = true

# Learn more about loading metafields on checkout resources, including the cart,
# products, and customers:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest#configuration

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest#configuration

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
